services:
  - type: web
    name: linkedin-management
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: linkedin-db
          property: connectionString

databases:
  - name: linkedin-db
    databaseName: linkedin_management
    user: linkedin_user